--
-- PostgreSQL database dump
--

\restrict M9G1Hmg1CRdqzgCL2L10hE4wbOCtgADZzqfcV3zdAPv5hpbt7apk00VmSaBBkM9

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-02-16 22:52:18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 7 (class 2615 OID 16676)
-- Name: sms; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA sms;


ALTER SCHEMA sms OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 245 (class 1259 OID 16980)
-- Name: attendances; Type: TABLE; Schema: sms; Owner: postgres
--

CREATE TABLE sms.attendances (
    attendance_id integer NOT NULL,
    enrollment_id integer NOT NULL,
    attendance_date date NOT NULL,
    status character varying,
    CONSTRAINT attendances_status_check CHECK (((status)::text = ANY ((ARRAY['ABSENT'::character varying, 'PRESENT'::character varying, 'LATE'::character varying])::text[])))
);


ALTER TABLE sms.attendances OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 16979)
-- Name: attendances_attendance_id_seq; Type: SEQUENCE; Schema: sms; Owner: postgres
--

ALTER TABLE sms.attendances ALTER COLUMN attendance_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sms.attendances_attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 16911)
-- Name: course_offerings; Type: TABLE; Schema: sms; Owner: postgres
--

CREATE TABLE sms.course_offerings (
    course_offering_id integer NOT NULL,
    course_id integer NOT NULL,
    section_code character varying NOT NULL,
    teacher_id integer NOT NULL,
    term_id integer NOT NULL,
    capacity integer,
    course_offering_created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE sms.course_offerings OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 16910)
-- Name: course_offerings_course_offering_id_seq; Type: SEQUENCE; Schema: sms; Owner: postgres
--

ALTER TABLE sms.course_offerings ALTER COLUMN course_offering_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sms.course_offerings_course_offering_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16740)
-- Name: courses; Type: TABLE; Schema: sms; Owner: postgres
--

CREATE TABLE sms.courses (
    course_id integer NOT NULL,
    course_code character varying NOT NULL,
    course_name character varying NOT NULL,
    course_units integer NOT NULL,
    course_created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE sms.courses OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16753)
-- Name: courses_course_id_seq; Type: SEQUENCE; Schema: sms; Owner: postgres
--

ALTER TABLE sms.courses ALTER COLUMN course_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sms.courses_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16720)
-- Name: curricula; Type: TABLE; Schema: sms; Owner: postgres
--

CREATE TABLE sms.curricula (
    curricula_id integer NOT NULL,
    program_id integer NOT NULL,
    academic_year character varying NOT NULL,
    version integer NOT NULL,
    is_active boolean NOT NULL,
    curricula_created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP CONSTRAINT curricula_created_at_not_null NOT NULL
);


ALTER TABLE sms.curricula OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16719)
-- Name: curricula_curricula_id_seq; Type: SEQUENCE; Schema: sms; Owner: postgres
--

ALTER TABLE sms.curricula ALTER COLUMN curricula_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sms.curricula_curricula_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16811)
-- Name: curriculum_courses; Type: TABLE; Schema: sms; Owner: postgres
--

CREATE TABLE sms.curriculum_courses (
    curriculum_course_id integer NOT NULL,
    curriculum_id integer NOT NULL,
    course_id integer NOT NULL,
    year_level integer NOT NULL,
    semester integer NOT NULL
);


ALTER TABLE sms.curriculum_courses OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16810)
-- Name: curriculum_courses_curriculum_course_id_seq; Type: SEQUENCE; Schema: sms; Owner: postgres
--

ALTER TABLE sms.curriculum_courses ALTER COLUMN curriculum_course_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sms.curriculum_courses_curriculum_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 16948)
-- Name: enrollments; Type: TABLE; Schema: sms; Owner: postgres
--

CREATE TABLE sms.enrollments (
    enrollment_id integer NOT NULL,
    student_id integer NOT NULL,
    course_offering_id integer NOT NULL,
    status character varying NOT NULL,
    prelim_grade numeric(5,2),
    midterm_grade numeric(5,2),
    tentative_final_grade numeric(5,2),
    final_grade numeric(5,2),
    intended_year_level integer,
    intended_semester integer,
    enrolled_at timestamp without time zone,
    completed_at time without time zone
);


ALTER TABLE sms.enrollments OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 16947)
-- Name: enrollments_enrollment_id_seq; Type: SEQUENCE; Schema: sms; Owner: postgres
--

ALTER TABLE sms.enrollments ALTER COLUMN enrollment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sms.enrollments_enrollment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16708)
-- Name: programs; Type: TABLE; Schema: sms; Owner: postgres
--

CREATE TABLE sms.programs (
    program_id integer NOT NULL,
    program_name character varying NOT NULL,
    program_created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP CONSTRAINT programs_created_at_not_null NOT NULL
);


ALTER TABLE sms.programs OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16678)
-- Name: roles; Type: TABLE; Schema: sms; Owner: postgres
--

CREATE TABLE sms.roles (
    role_id integer NOT NULL,
    role_name character varying
);


ALTER TABLE sms.roles OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16677)
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: sms; Owner: postgres
--

ALTER TABLE sms.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sms.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 17000)
-- Name: student_curriculum_progress; Type: TABLE; Schema: sms; Owner: postgres
--

CREATE TABLE sms.student_curriculum_progress (
    curriculum_progress_id integer NOT NULL,
    student_id integer NOT NULL,
    curriculum_course_id integer NOT NULL,
    status character varying NOT NULL,
    final_grade numeric(5,2),
    completed_at timestamp without time zone
);


ALTER TABLE sms.student_curriculum_progress OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 16999)
-- Name: student_curriculum_progress_curriculum_progress_id_seq; Type: SEQUENCE; Schema: sms; Owner: postgres
--

ALTER TABLE sms.student_curriculum_progress ALTER COLUMN curriculum_progress_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sms.student_curriculum_progress_curriculum_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16833)
-- Name: students; Type: TABLE; Schema: sms; Owner: postgres
--

CREATE TABLE sms.students (
    student_id integer NOT NULL,
    user_id integer NOT NULL,
    first_name character varying NOT NULL,
    middle_name character varying NOT NULL,
    last_name character varying NOT NULL,
    date_of_birth date NOT NULL,
    program_id integer NOT NULL,
    curriculum_id integer NOT NULL,
    year_level integer DEFAULT 1,
    is_irregular boolean DEFAULT false NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    graduated_at date,
    student_created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE sms.students OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16874)
-- Name: students_student_id_seq; Type: SEQUENCE; Schema: sms; Owner: postgres
--

ALTER TABLE sms.students ALTER COLUMN student_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sms.students_student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16876)
-- Name: teachers; Type: TABLE; Schema: sms; Owner: postgres
--

CREATE TABLE sms.teachers (
    teacher_id integer NOT NULL,
    user_id integer NOT NULL,
    first_name character varying NOT NULL,
    middle_name character varying NOT NULL,
    last_name character varying NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    left_at date,
    teacher_created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE sms.teachers OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16875)
-- Name: teachers_teacher_id_seq; Type: SEQUENCE; Schema: sms; Owner: postgres
--

ALTER TABLE sms.teachers ALTER COLUMN teacher_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sms.teachers_teacher_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 16897)
-- Name: terms; Type: TABLE; Schema: sms; Owner: postgres
--

CREATE TABLE sms.terms (
    term_id integer CONSTRAINT "Terms_term_id_not_null" NOT NULL,
    term_name character varying CONSTRAINT "Terms_term_name_not_null" NOT NULL,
    start_date date CONSTRAINT "Terms_start_date_not_null" NOT NULL,
    end_date date CONSTRAINT "Terms_end_date_not_null" NOT NULL,
    is_active boolean DEFAULT true CONSTRAINT "Terms_is_active_not_null" NOT NULL
);


ALTER TABLE sms.terms OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 16942)
-- Name: terms_term_id_seq; Type: SEQUENCE; Schema: sms; Owner: postgres
--

ALTER TABLE sms.terms ALTER COLUMN term_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sms.terms_term_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16689)
-- Name: users; Type: TABLE; Schema: sms; Owner: postgres
--

CREATE TABLE sms.users (
    user_id integer NOT NULL,
    username character varying NOT NULL,
    password_hash text NOT NULL,
    role_id integer NOT NULL,
    user_email character varying CONSTRAINT users_email_not_null NOT NULL,
    user_created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP CONSTRAINT users_created_at_not_null NOT NULL
);


ALTER TABLE sms.users OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16688)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: sms; Owner: postgres
--

ALTER TABLE sms.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sms.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5165 (class 0 OID 16980)
-- Dependencies: 245
-- Data for Name: attendances; Type: TABLE DATA; Schema: sms; Owner: postgres
--

COPY sms.attendances (attendance_id, enrollment_id, attendance_date, status) FROM stdin;
\.


--
-- TOC entry 5160 (class 0 OID 16911)
-- Dependencies: 240
-- Data for Name: course_offerings; Type: TABLE DATA; Schema: sms; Owner: postgres
--

COPY sms.course_offerings (course_offering_id, course_id, section_code, teacher_id, term_id, capacity, course_offering_created_at) FROM stdin;
\.


--
-- TOC entry 5150 (class 0 OID 16740)
-- Dependencies: 230
-- Data for Name: courses; Type: TABLE DATA; Schema: sms; Owner: postgres
--

COPY sms.courses (course_id, course_code, course_name, course_units, course_created_at) FROM stdin;
\.


--
-- TOC entry 5149 (class 0 OID 16720)
-- Dependencies: 229
-- Data for Name: curricula; Type: TABLE DATA; Schema: sms; Owner: postgres
--

COPY sms.curricula (curricula_id, program_id, academic_year, version, is_active, curricula_created_at) FROM stdin;
\.


--
-- TOC entry 5153 (class 0 OID 16811)
-- Dependencies: 233
-- Data for Name: curriculum_courses; Type: TABLE DATA; Schema: sms; Owner: postgres
--

COPY sms.curriculum_courses (curriculum_course_id, curriculum_id, course_id, year_level, semester) FROM stdin;
\.


--
-- TOC entry 5163 (class 0 OID 16948)
-- Dependencies: 243
-- Data for Name: enrollments; Type: TABLE DATA; Schema: sms; Owner: postgres
--

COPY sms.enrollments (enrollment_id, student_id, course_offering_id, status, prelim_grade, midterm_grade, tentative_final_grade, final_grade, intended_year_level, intended_semester, enrolled_at, completed_at) FROM stdin;
\.


--
-- TOC entry 5147 (class 0 OID 16708)
-- Dependencies: 227
-- Data for Name: programs; Type: TABLE DATA; Schema: sms; Owner: postgres
--

COPY sms.programs (program_id, program_name, program_created_at) FROM stdin;
\.


--
-- TOC entry 5144 (class 0 OID 16678)
-- Dependencies: 224
-- Data for Name: roles; Type: TABLE DATA; Schema: sms; Owner: postgres
--

COPY sms.roles (role_id, role_name) FROM stdin;
\.


--
-- TOC entry 5167 (class 0 OID 17000)
-- Dependencies: 247
-- Data for Name: student_curriculum_progress; Type: TABLE DATA; Schema: sms; Owner: postgres
--

COPY sms.student_curriculum_progress (curriculum_progress_id, student_id, curriculum_course_id, status, final_grade, completed_at) FROM stdin;
\.


--
-- TOC entry 5154 (class 0 OID 16833)
-- Dependencies: 234
-- Data for Name: students; Type: TABLE DATA; Schema: sms; Owner: postgres
--

COPY sms.students (student_id, user_id, first_name, middle_name, last_name, date_of_birth, program_id, curriculum_id, year_level, is_irregular, is_active, graduated_at, student_created_at) FROM stdin;
\.


--
-- TOC entry 5157 (class 0 OID 16876)
-- Dependencies: 237
-- Data for Name: teachers; Type: TABLE DATA; Schema: sms; Owner: postgres
--

COPY sms.teachers (teacher_id, user_id, first_name, middle_name, last_name, is_active, left_at, teacher_created_at) FROM stdin;
\.


--
-- TOC entry 5158 (class 0 OID 16897)
-- Dependencies: 238
-- Data for Name: terms; Type: TABLE DATA; Schema: sms; Owner: postgres
--

COPY sms.terms (term_id, term_name, start_date, end_date, is_active) FROM stdin;
\.


--
-- TOC entry 5146 (class 0 OID 16689)
-- Dependencies: 226
-- Data for Name: users; Type: TABLE DATA; Schema: sms; Owner: postgres
--

COPY sms.users (user_id, username, password_hash, role_id, user_email, user_created_at) FROM stdin;
\.


--
-- TOC entry 5173 (class 0 OID 0)
-- Dependencies: 244
-- Name: attendances_attendance_id_seq; Type: SEQUENCE SET; Schema: sms; Owner: postgres
--

SELECT pg_catalog.setval('sms.attendances_attendance_id_seq', 1, false);


--
-- TOC entry 5174 (class 0 OID 0)
-- Dependencies: 239
-- Name: course_offerings_course_offering_id_seq; Type: SEQUENCE SET; Schema: sms; Owner: postgres
--

SELECT pg_catalog.setval('sms.course_offerings_course_offering_id_seq', 1, false);


--
-- TOC entry 5175 (class 0 OID 0)
-- Dependencies: 231
-- Name: courses_course_id_seq; Type: SEQUENCE SET; Schema: sms; Owner: postgres
--

SELECT pg_catalog.setval('sms.courses_course_id_seq', 1, false);


--
-- TOC entry 5176 (class 0 OID 0)
-- Dependencies: 228
-- Name: curricula_curricula_id_seq; Type: SEQUENCE SET; Schema: sms; Owner: postgres
--

SELECT pg_catalog.setval('sms.curricula_curricula_id_seq', 1, false);


--
-- TOC entry 5177 (class 0 OID 0)
-- Dependencies: 232
-- Name: curriculum_courses_curriculum_course_id_seq; Type: SEQUENCE SET; Schema: sms; Owner: postgres
--

SELECT pg_catalog.setval('sms.curriculum_courses_curriculum_course_id_seq', 1, false);


--
-- TOC entry 5178 (class 0 OID 0)
-- Dependencies: 242
-- Name: enrollments_enrollment_id_seq; Type: SEQUENCE SET; Schema: sms; Owner: postgres
--

SELECT pg_catalog.setval('sms.enrollments_enrollment_id_seq', 1, false);


--
-- TOC entry 5179 (class 0 OID 0)
-- Dependencies: 223
-- Name: roles_role_id_seq; Type: SEQUENCE SET; Schema: sms; Owner: postgres
--

SELECT pg_catalog.setval('sms.roles_role_id_seq', 1, false);


--
-- TOC entry 5180 (class 0 OID 0)
-- Dependencies: 246
-- Name: student_curriculum_progress_curriculum_progress_id_seq; Type: SEQUENCE SET; Schema: sms; Owner: postgres
--

SELECT pg_catalog.setval('sms.student_curriculum_progress_curriculum_progress_id_seq', 1, false);


--
-- TOC entry 5181 (class 0 OID 0)
-- Dependencies: 235
-- Name: students_student_id_seq; Type: SEQUENCE SET; Schema: sms; Owner: postgres
--

SELECT pg_catalog.setval('sms.students_student_id_seq', 1, false);


--
-- TOC entry 5182 (class 0 OID 0)
-- Dependencies: 236
-- Name: teachers_teacher_id_seq; Type: SEQUENCE SET; Schema: sms; Owner: postgres
--

SELECT pg_catalog.setval('sms.teachers_teacher_id_seq', 1, false);


--
-- TOC entry 5183 (class 0 OID 0)
-- Dependencies: 241
-- Name: terms_term_id_seq; Type: SEQUENCE SET; Schema: sms; Owner: postgres
--

SELECT pg_catalog.setval('sms.terms_term_id_seq', 1, false);


--
-- TOC entry 5184 (class 0 OID 0)
-- Dependencies: 225
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: sms; Owner: postgres
--

SELECT pg_catalog.setval('sms.users_user_id_seq', 1, false);


--
-- TOC entry 4963 (class 2606 OID 16909)
-- Name: terms Terms_pkey; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.terms
    ADD CONSTRAINT "Terms_pkey" PRIMARY KEY (term_id);


--
-- TOC entry 4973 (class 2606 OID 16990)
-- Name: attendances attendances_enrollment_id_attendance_date_key; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.attendances
    ADD CONSTRAINT attendances_enrollment_id_attendance_date_key UNIQUE (enrollment_id, attendance_date);


--
-- TOC entry 4975 (class 2606 OID 16998)
-- Name: attendances attendances_pkey; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.attendances
    ADD CONSTRAINT attendances_pkey PRIMARY KEY (attendance_id);


--
-- TOC entry 4947 (class 2606 OID 16873)
-- Name: courses course_code; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.courses
    ADD CONSTRAINT course_code UNIQUE (course_code);


--
-- TOC entry 4949 (class 2606 OID 16809)
-- Name: courses course_id; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.courses
    ADD CONSTRAINT course_id UNIQUE (course_id);


--
-- TOC entry 4965 (class 2606 OID 16926)
-- Name: course_offerings course_offerings_course_id_section_code_term_id_key; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.course_offerings
    ADD CONSTRAINT course_offerings_course_id_section_code_term_id_key UNIQUE (course_id, section_code, term_id);


--
-- TOC entry 4967 (class 2606 OID 16924)
-- Name: course_offerings course_offerings_pkey; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.course_offerings
    ADD CONSTRAINT course_offerings_pkey PRIMARY KEY (course_offering_id);


--
-- TOC entry 4951 (class 2606 OID 16752)
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (course_id, course_code, course_name, course_units);


--
-- TOC entry 4945 (class 2606 OID 16733)
-- Name: curricula curricula_pkey; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.curricula
    ADD CONSTRAINT curricula_pkey PRIMARY KEY (curricula_id);


--
-- TOC entry 4953 (class 2606 OID 16822)
-- Name: curriculum_courses curriculum_courses_curriculum_id_course_id_key; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.curriculum_courses
    ADD CONSTRAINT curriculum_courses_curriculum_id_course_id_key UNIQUE (curriculum_id, course_id);


--
-- TOC entry 4955 (class 2606 OID 16820)
-- Name: curriculum_courses curriculum_courses_pkey; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.curriculum_courses
    ADD CONSTRAINT curriculum_courses_pkey PRIMARY KEY (curriculum_course_id);


--
-- TOC entry 4969 (class 2606 OID 16958)
-- Name: enrollments enrollments_pkey; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.enrollments
    ADD CONSTRAINT enrollments_pkey PRIMARY KEY (enrollment_id);


--
-- TOC entry 4933 (class 2606 OID 16996)
-- Name: enrollments enrollments_status_check; Type: CHECK CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE sms.enrollments
    ADD CONSTRAINT enrollments_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DROPPED'::character varying, 'COMPLETED'::character varying])::text[]))) NOT VALID;


--
-- TOC entry 4971 (class 2606 OID 16960)
-- Name: enrollments enrollments_student_id_course_offering_id_key; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.enrollments
    ADD CONSTRAINT enrollments_student_id_course_offering_id_key UNIQUE (student_id, course_offering_id);


--
-- TOC entry 4943 (class 2606 OID 16718)
-- Name: programs programs_pkey; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.programs
    ADD CONSTRAINT programs_pkey PRIMARY KEY (program_id);


--
-- TOC entry 4937 (class 2606 OID 16685)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- TOC entry 4939 (class 2606 OID 16687)
-- Name: roles roles_role_name_key; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.roles
    ADD CONSTRAINT roles_role_name_key UNIQUE (role_name);


--
-- TOC entry 4977 (class 2606 OID 17010)
-- Name: student_curriculum_progress student_curriculum_progress_pkey; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.student_curriculum_progress
    ADD CONSTRAINT student_curriculum_progress_pkey PRIMARY KEY (curriculum_progress_id);


--
-- TOC entry 4935 (class 2606 OID 17023)
-- Name: student_curriculum_progress student_curriculum_progress_status_check; Type: CHECK CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE sms.student_curriculum_progress
    ADD CONSTRAINT student_curriculum_progress_status_check CHECK (((status)::text = ANY ((ARRAY['NOT_TAKEN'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[]))) NOT VALID;


--
-- TOC entry 4979 (class 2606 OID 17012)
-- Name: student_curriculum_progress student_curriculum_progress_student_id_curriculum_course_id_key; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.student_curriculum_progress
    ADD CONSTRAINT student_curriculum_progress_student_id_curriculum_course_id_key UNIQUE (student_id, curriculum_course_id);


--
-- TOC entry 4957 (class 2606 OID 16854)
-- Name: students students_pkey; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (student_id);


--
-- TOC entry 4959 (class 2606 OID 16856)
-- Name: students students_user_id_key; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.students
    ADD CONSTRAINT students_user_id_key UNIQUE (user_id);


--
-- TOC entry 4961 (class 2606 OID 16891)
-- Name: teachers teachers_pkey; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.teachers
    ADD CONSTRAINT teachers_pkey PRIMARY KEY (teacher_id);


--
-- TOC entry 4941 (class 2606 OID 16702)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- TOC entry 4993 (class 2606 OID 16991)
-- Name: attendances attendances_enrollment_id_fkey; Type: FK CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.attendances
    ADD CONSTRAINT attendances_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES sms.enrollments(enrollment_id);


--
-- TOC entry 4988 (class 2606 OID 16927)
-- Name: course_offerings course_offerings_course_id_fkey; Type: FK CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.course_offerings
    ADD CONSTRAINT course_offerings_course_id_fkey FOREIGN KEY (course_id) REFERENCES sms.courses(course_id);


--
-- TOC entry 4989 (class 2606 OID 16932)
-- Name: course_offerings course_offerings_teacher_id_fkey; Type: FK CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.course_offerings
    ADD CONSTRAINT course_offerings_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES sms.teachers(teacher_id);


--
-- TOC entry 4990 (class 2606 OID 16937)
-- Name: course_offerings course_offerings_term_id_fkey; Type: FK CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.course_offerings
    ADD CONSTRAINT course_offerings_term_id_fkey FOREIGN KEY (term_id) REFERENCES sms.terms(term_id);


--
-- TOC entry 4981 (class 2606 OID 16734)
-- Name: curricula curricula_program_id_fkey; Type: FK CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.curricula
    ADD CONSTRAINT curricula_program_id_fkey FOREIGN KEY (program_id) REFERENCES sms.programs(program_id) ON DELETE CASCADE;


--
-- TOC entry 4982 (class 2606 OID 16828)
-- Name: curriculum_courses curriculum_courses_course_id_fkey; Type: FK CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.curriculum_courses
    ADD CONSTRAINT curriculum_courses_course_id_fkey FOREIGN KEY (course_id) REFERENCES sms.courses(course_id);


--
-- TOC entry 4983 (class 2606 OID 16823)
-- Name: curriculum_courses curriculum_courses_curriculum_id_fkey; Type: FK CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.curriculum_courses
    ADD CONSTRAINT curriculum_courses_curriculum_id_fkey FOREIGN KEY (curriculum_id) REFERENCES sms.curricula(curricula_id) ON DELETE CASCADE;


--
-- TOC entry 4991 (class 2606 OID 16966)
-- Name: enrollments enrollments_course_offering_id_fkey; Type: FK CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.enrollments
    ADD CONSTRAINT enrollments_course_offering_id_fkey FOREIGN KEY (course_offering_id) REFERENCES sms.course_offerings(course_offering_id);


--
-- TOC entry 4992 (class 2606 OID 16961)
-- Name: enrollments enrollments_student_id_fkey; Type: FK CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.enrollments
    ADD CONSTRAINT enrollments_student_id_fkey FOREIGN KEY (student_id) REFERENCES sms.students(student_id);


--
-- TOC entry 4994 (class 2606 OID 17018)
-- Name: student_curriculum_progress student_curriculum_progress_curriculum_course_id_fkey; Type: FK CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.student_curriculum_progress
    ADD CONSTRAINT student_curriculum_progress_curriculum_course_id_fkey FOREIGN KEY (curriculum_course_id) REFERENCES sms.curriculum_courses(curriculum_course_id) ON DELETE CASCADE;


--
-- TOC entry 4995 (class 2606 OID 17013)
-- Name: student_curriculum_progress student_curriculum_progress_student_id_fkey; Type: FK CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.student_curriculum_progress
    ADD CONSTRAINT student_curriculum_progress_student_id_fkey FOREIGN KEY (student_id) REFERENCES sms.students(student_id) ON DELETE CASCADE;


--
-- TOC entry 4984 (class 2606 OID 16867)
-- Name: students students_curriculum_id_fkey; Type: FK CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.students
    ADD CONSTRAINT students_curriculum_id_fkey FOREIGN KEY (curriculum_id) REFERENCES sms.curricula(curricula_id);


--
-- TOC entry 4985 (class 2606 OID 16862)
-- Name: students students_program_id_fkey; Type: FK CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.students
    ADD CONSTRAINT students_program_id_fkey FOREIGN KEY (program_id) REFERENCES sms.programs(program_id);


--
-- TOC entry 4986 (class 2606 OID 16857)
-- Name: students students_user_id_fkey; Type: FK CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.students
    ADD CONSTRAINT students_user_id_fkey FOREIGN KEY (user_id) REFERENCES sms.users(user_id) ON DELETE CASCADE;


--
-- TOC entry 4987 (class 2606 OID 16892)
-- Name: teachers teachers_user_id_fkey; Type: FK CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.teachers
    ADD CONSTRAINT teachers_user_id_fkey FOREIGN KEY (user_id) REFERENCES sms.users(user_id);


--
-- TOC entry 4980 (class 2606 OID 16703)
-- Name: users users_role_id_fkey; Type: FK CONSTRAINT; Schema: sms; Owner: postgres
--

ALTER TABLE ONLY sms.users
    ADD CONSTRAINT users_role_id_fkey FOREIGN KEY (role_id) REFERENCES sms.roles(role_id);


-- Completed on 2026-02-16 22:52:18

--
-- PostgreSQL database dump complete
--

\unrestrict M9G1Hmg1CRdqzgCL2L10hE4wbOCtgADZzqfcV3zdAPv5hpbt7apk00VmSaBBkM9

